### PR TITLE
Added a global break

### PR DESCRIPTION
**Pull request by Wouterz90**
In a game we came to the conclusion that this might be useful, so I thought why not make it.

### CODE REVIEW

**Comment by darklordabc** [comment]
Well its definitely going to be more useful than global silence.

**Comment by Jexah** [comment]
Can you please change the code references of `global_break` to `silencer_global_break` to conform to the standard? Not to say that the skill will make it in the game, you should follow the standard if you want it in LoD.

**Comment by darklordabc** [comment]
Tested, and it doesn't break passives yet. Also it plays that missing animation graphic of the weird little red "+".

**Comment by darklordabc** [comment]
Actually it does seem to break passives, my bad.

**Comment by darklordabc** [comment]
image

**Comment by Wouterz90** [comment]
Thank you for doing those changers for me, I thought I copy pasted the different particles already because I wasn't satisfied with the old ones. Silver edge's effect means break to most people I guess.

**Comment by ash47** [comment]
I will need to do some testing before I merge this, seems like an ok idea.

**Comment by ash47** [comment]
My own personal backup of this: https://github.com/LegendsOfDota/LegendsOfDota/tree/global_break

**Pull request closed without merging**
