### PR TITLE
Illusion hotfix for custom essence shifts

### PR DESCRIPTION
**Pull request by Myrl**

### CODE REVIEW

**Comment by darklordabc** [comment]
Tested and it works. Illusions dont steal, and you can't steal from illusions.

**Comment by darklordabc** [comment]
If anyone can be bothered, maybe push this to the spell library.

**Comment by ash47** [comment]
You really need to learn about precedence in programming, "not" has a higher precedence than "and" meaning that adding the brackets does not actually do anything in your code.

I will merge because I am not too fussed about this.

**Comment by Myrl** [comment]
@ash47 Hahaha, sorry. I sometimes forget the precedence and also work with other languages. I just did that to ensure that it will be correct.

**Comment by Jexah** [comment]
Lol which language puts 'not' at a lower initiative than 'and'?

To be fair though, it can be helpful for the next person if it makes it
much easier to read. Given that I haven't read the code myself I can't
really judge.

**Comment by Myrl** [comment]
@Jexah Probably none. Lol.

**Pull request merged**
