### PR TITLE
Team switch button

### PR DESCRIPTION
**Pull request by Myrl**
This is meant to supersede #322 in the implementation of #274.

This does not yet conform to the coding style since #322's attempt to conform broke the code.

The difference between this and #322 is that this will now hide connected players. This also fixed a lot of hidden bugs such as the [ingame.lua](https://github.com/LegendsOfDota/LegendsOfDota/pull/343/commits/02c14b170bf63a2ea5c7713db79d3b7c50132eef#diff-3f097b13ee14994badb05acb9a30e05cR79). I also condensed it into a single swap event, for security and practicality purposes.

### Team Switch Button
switchbutton3
*Button added to top left.
*Notification pops up when teams become unbalanced (more than 2 player advantage). Goes away after 20 seconds or when player clicks switch button.
*Shows list of all abandoned players that you can switch with. Clicking any will commence team switch vote.
*Player's disconnected for longer than 5 minutes will be regarded as abandoned, and thus switchable. 
### Vote Popup
votepopup
*Popup comes up when switch proposed. 
*Game pauses while vote is taking place.
*Vote will end early if anyone declines, or if all people agree. 
### Courier features
*Courier control swaps properly. Lose control of old courier, gain control of new team's courier.
*Items left behind in old team's courier are removed and refunded to player.
### Other Features
*Abilities that leave entities behind are dealt with. E.g. mines, bears, familars are destroyed, eyes in the Forest, Webs, Psionic Traps are swapped to the right team etc.

### CODE REVIEW

**Comment by darklordabc** [comment]
This is working surprisingly well so far.

**Comment by darklordabc** [comment]
This still needs testing.

**Comment by darklordabc** [comment]
Stll WIP.
Todo:
Deal with courier control.
Deal with items left behind in courier.
Maybe deal with some special cases like bear not switching or eyes in forests not switching etc.

**Comment by darklordabc** [comment]
@ash47 this has been tested quite a bit, and it _seems_ to be working perfectly and effectively, but still can't promise it is bug free. When you get free time, please review the code and merge it if it passes muster. 
Any problems, let us know and we can get it fixed up asap.

**Comment by ash47** [comment]
I'll try it out in game to see if it feels natural, but this is another feature I am still not sold on. Will perform a code review once I think the feature is acceptable to merge.

**Comment by darklordabc** [comment]
This is in my opinion the only really needed feature right now. I dont think you have to worry much about it feeling unnatural as it can only pass if everybody agrees, so it cant piss anyone off really.

**Comment by ash47** [comment]
I'll be the judge of that.

**Comment by darklordabc** [comment]
Duh

**Comment by ash47** [comment]
Why even reply? Adding duh just adds a notification for me to read and
slows this whole process down

**Comment by darklordabc** [comment]
I could say the same with obvious unconstructive crap like "I'll be the judge".

**Comment by ash47** [comment]
Posting smart ass comments and wasting my time is the right way to go about
getting yourself banned from the repository.

**Comment by darklordabc** [comment]
I think its a bit rich to say I'm wasting your time when I've spent literally hours and hours improving this mod, and bug-fixing, hence saving you much more time.

**Comment by ash47** [comment]
You realise that YOU are the reason I stopped working on this mod in the
first place right? You have wasted more of my time than you have "saved". I
stopped working on this mod because of all the BS extra work you gave me,
it lost its fun element, and just become a chore because of you.

You're also the reason I no longer (or rarely) go onto the steam forums for
LoD, I used to read every message on there (and reply where necessary), now
you just spam every thread so I have disabled the notifications from it, as
I am sick of getting notifications from you.

Everyone in my programming circle has told me to just ban you from the
community, so you're lucky I am in charge, if @jexah or @jimmydorry or any
of my other friends had their way, you'd of been banned long ago.

It's incredibly easy for me to just turn off notifications and ignore all
the community contributions, and it seems like that is your goal here, to
piss me off enough that I leave.

After all this, you're still continuing to waste my time by arguing and
protecting that you're in the right.

Reply to this and see what happens. You've been warned. I'm sick of your
shit.

**Comment by ash47** [comment]
Your loss, not mine.

**Comment by ash47** [comment]
My own personal backup of this: https://github.com/LegendsOfDota/LegendsOfDota/tree/team_switch

**Pull request closed without merging**
